apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    CLOUDFLAIR_EMAIL: AgCgXZJHH82jqzboA0HrT1GK36EkCzfmS0PI8XE9c1SiD3pdWiy+6HEt8XOrwH+TywRhMeqaEAmVT0v29I4SX0Yj8fRGZqqmH63Vn4qiSB+pB0ruPUKXYjMjgMlK6YxkVwr7U+UYSOEdsqi980glLyjMLp2N7n7xABOcsBtZ2c6rEhtZ7h8xlWNsA1kAOzFxlc0UghgMjbLscP8tf/wWF78vHZQ34RH0TMjR4DD6VffFGoJlMQmLL4A1gjZaeNYzxGa94YEKcdX0tIjD39DfXGsprk/cxUC0Oj0jlR3Xw1Mgo5baFl/FFduRRpiyj2Fs7AHpIsqebNZsPfql7IaAe65gaQHKWG7MfU8dhmZtwsmVQTCVL1LWTjPZjTsxNJrqXUzxaIrPhmDBWYaC+4cgj/9lRktkMqESsu71j1Gj5UZqO9gmvX3F1ucurRCFr6vBfy33rr8P1LP2mmhdcq0ujQV8Z+mDlkLxqfqyzS/rdjLBMiamnlD2prdJ144fwT55l8K2OVDA6G6OQrjHJioRfnZGL+QYKjAewJnB96Uwb21LPL+thoDn+ZJ2Dmt7IEOqagef1ppI5Ai5rNnGddRCIq7UX0qBnjxcEf9F1SztkZBghMOdKD8/tSkTpo46Nj1jou2u4QaylLhvXkUt5nXMRX1eXSR8WadRmXVvKpPzTaahynQAamFXfZFYWZiLxXS2sZjPFdr0r5FiT2Metg0FgTvwxOBlNg==
    CLOUDFLAIR_TOKEN: AgBFVdBUfzy6XFSpZmFlXySz3oHev6pvjnF/l13Oo4aT70dyg2+nJc/mP5KPDOSXgPaBIQa8ObXtetAHi5dlbig3jY5/awY5yc3SNCx2lvbkkIDTG6pe96cFXFITJmRrl0gLdXnNoqNya4q9Ayuvd13HYXMl7h5OtaPw6AzDUY8FAODWKcLt+BhXZaEelfC9mSvaPi4Ma0xHAPgc7oXZeUM/zoPrZzuoe3PxbzB6yTDPSYVIsjWEakRHam/u6hXB7MaNA8bq1U6UkSnWqJnXGOYnCGyN2SBXNEw3rT7hsPjZknigo+bo4T2a/Q5gmtf6cbLvcC0UryPvEt+F1uSzC5gwdYkpdXDgSg+Iog4/dMVOs91ZzAOwYjv2pkjYrWuNWU7ri8l85XFpVwAST8SqcxO0I3Qy32At/2/bjp94rTJ7vPK9/r69NKTWo9a4Gnf4ksfRcKaB5wMd61KrCsQLlwbts7ArQlI3aHY9V51NWuJxDnKGF2HiNrDsVk5tg/IaX5buT1bMCVnLO2NUXr6vO2KQ1vaJd82urfFl9+tSO14uHSf8+0pcU54C2qZJuo6rJMtdqSn2bUwdCLy0VK510ZBnu8wZ0JT/rWqq89s2IraNrrbfzszp47E6th8AR7oQ6WYaJ0hjY3yJj+3DNkT0gSrNpoCGiigw8L8FSX5JI/DUQtzf9hRvj3ZY4klj+ZRkt4iWXxcxViZgcQG/EBAHsoYVRhPSUiSx0O0u961prb5BUH9zjozklSoB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret