apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fts-frontend
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
        targetRevision: master
        path: configs/fts/fts-frontend/dev
      - env: prod
        repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
        targetRevision: master
        path: configs/fts/fts-frontend/prod
  template:
    metadata:
      name: fts-frontend-{{env}}
      namespace: argocd
    spec:
      project: fts
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        helm:
          releaseName: fts-frontend
      destination:
        name: in-cluster
        namespace: fts-frontend-{{env}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true