apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-blog
  namespace: argocd
  
spec:
  project: fts
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/fts/ghost-blog
    # Deploy application using helm
    helm:
      releaseName: ghost-blog
  destination:
    name: in-cluster
    namespace: ghost-blog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true