longhorn:
  ingress:
    enabled: true
    host: longhorn.k8s.frontenac.tech
    tls: true
    tlsSecret: longhorn.k8s.frontenac.tech
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"