apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator
  namespace: argocd  
spec:
  project: kubernetes
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/kubernetes/cloudflare-operator
    # Deploy application using helm
    helm:
      releaseName: cloudflare-operator
  destination:
    name: in-cluster
    namespace: cloudflare-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator-configs
  namespace: argocd  
spec:
  project: kubernetes
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/kubernetes/cloudflare-operator/configs
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: cloudflare-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true