# Create ArgoCD bootstrap application (App of Apps)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns
  namespace: argocd
  
spec:
  project: kubernetes
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/kubernetes/ddns
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: ddns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true