apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smtp
  namespace: argocd
  
spec:
  project: kubernetes
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/kubernetes/smtp
    # Deploy application using helm
    helm:
      releaseName: smtp
  destination:
    name: in-cluster
    namespace: smtp
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true