apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
  
spec:
  project: sso
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/sso/openldap
    # Deploy application using helm
    helm:
      releaseName: openldap
  destination:
    name: in-cluster
    namespace: openldap
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
  
spec:
  project: sso
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/sso/openldap/configs
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: openldap
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true