apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
      postgres-password: AgB3xb2Zxo57ZSW6TOjunIhlIZdywgYMOY07NS3Gd8UtPVv9aTtt0Ph8q2xvlhxmq1M142O8UV45mjbAcVW5CamaYPKwxeltRM/6kqKcMpmC4+wbPTvceiQkbBAGU4ciJXsStzMCUNdTj6EGYbxEJPIy33uecsAShG4OTDRjErC7y7EifgaTfuPiohLIdL7qKO7KpV6x5117xlijfWkV1yOCBQUFgls/4ylCYL2o0pN5wAAiCq8eKDbunlXFpCssmAXUyhs+70wxOCHN9/j7ppYMQLwkIxAXxvVPO+gl806WDONVVqFDbvxX0N+vTWv0S3i5mPbcOyQoa+SmkwGpjHtas+ND1Y9OqJ6i1zjthMs8W1ey6WpRCu4dcKXerS0mkZrmUmR1CcJG8IG6MyxSfCTpuUA5xEiF73oFYmHMBpPv2Zvh5iPOqHTNy9cBU3xHANySIOP0QqjCC+KjYWYg7rn3wpGtsl9TcTYiiduAQqdpgwEXwOSkHIqxcmeVe7z3FmaN6R0SShlm+TX4/kDlgt82+XdrjTXwLDLQyYu/W7yPQDasU2D+VpAtRXZnJaw8bYTbc8d019MPKP6NzvvvXvKC2LEmh7nmgiqzbrDyjnKKrwqvbm5LgdR+Vq92IBqWsoTZR/K/MWUzRHxNSzZk6jUj1uv6fimCJw53mj6wizJmKpWBSlblBZIdQEV6WFY7bfb+kH823gMZ+M/UOLTfzxEfds5SDBBU2+YY0hWQI5O51g==
      password: AgCtcb64amladR3x4EU3w2gLZqk2sukR5oY+NUwAPoQD2n5o9qrKMQuHxg+n0b7rDonjap0g+MIjdluvC0JqUM8M+aiZOJqaKu3h4zdcnF7W6uq8VsLbX/DGtL2hioncD2EbM/V9wOmP7ZFnNV2ofEICTFaR2SeTg5iYxq7q2hMW7ssGuy3pN2P+GmRXQoniIMHZFBSoQiqvxZQhzeGnC6G55WSu6E0y2z7rTmVkgR4wHI3asq3p1bKOFVwAtCOf4SvMk309L/jr+4sYCzbpbSw1tC0YWnukBrLPy75WNGWFSK6DH7naVVBIJ6ZrcbqaOlYlPT+OjwQf9msdrEIIISQ+73m2y1Saif+orVmqR6GiHPBzQcBvo/kCy+sPZNLP2ctK+1f2vzntu5r8PlS8rHVAVCZXhoZChq8qD23e1FZizFidHiY74XVun1GGHFBGXsZknOCOxBHxZyrruO3YoNs9RCVw0qmnohjBihI1QeelOisAtT/6noEYU01BD6ScycEUD0Lgijsi7pn3EryEqvh/ixGyX04rBMGyCPuALj5z9fWEpyAHhKVNeEo1WpyXqdG1eatogkt+u9erndxCRtgsdtVEf5RUwL74p9umx324V51dTJsZY4CRf3j/JQtxv5bqaq/rhScadH6SCXv7WGmbNpwA/F3L8oVUCZeklX+OV+SvIYUIdYqi4h9zzo7nU59jRNme/oKs0eFzpRm3V491/a0LRIuRwteMxLxZ06vtXQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret