apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cockroachdb
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
        targetRevision: master
        path: configs/managed-services/cockroachdb/dev
      # - env: prod
      #   repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
      #   targetRevision: master
      #   path: configs/managed-services/cockroachdb/prod
  template:
    metadata:
      name: cockroachdb-{{env}}
      namespace: argocd
    spec:
      project: managed-services
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        name: in-cluster
        namespace: cockroach-operator-system-{{env}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true