apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
  
spec:
  project: managed-services
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/managed-services/seafile
    # Deploy application using helm
    helm:
      releaseName: seafile
  destination:
    name: in-cluster
    namespace: seafile
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile-secrets
  namespace: argocd  
spec:
  project: managed-services
  source:
    repoURL: git@github.com:Frontenac-Technology-Services/k8s-configs.git
    targetRevision: master
    path: configs/managed-services/seafile/secrets
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: seafile
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true