apiVersion: cf.containeroo.ch/v1beta1
kind: IP
metadata:
  name: dynamic-external-ipv4-address
spec:
  type: dynamic
  interval: 2m0s
  ipSources:
    - requestHeadersSecretRef: {}
      requestMethod: GET
      url: 'https://ipecho.net/plain'
    - requestHeadersSecretRef: {}
      requestMethod: GET
      url: 'https://ifconfig.me/ip'
    - requestHeadersSecretRef: {}
      requestMethod: GET
      url: 'https://checkip.amazonaws.com'
    - requestHeadersSecretRef: {}
      requestMethod: GET
      url: 'https://api.ipify.org'
    - requestHeadersSecretRef: {}
      requestMethod: GET
      url: 'https://myip.is/ip/'