apiVersion: v2
name: openldap
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
- alias: openldap
  name: openldap-stack-ha
  version: 3.0.0
  repository: https://jp-gouin.github.io/helm-openldap/